# Generated by Django 5.2.10 on 2026-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
