# Generated by Django 5.2.10 on 2026-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reports',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
